### ISSUE TITLE
Long running tasks are not cancelled on view dissapear

### ISSUE THREAD

**Issue by sisoje** [SwiftedMind/Processed#2]
Steps to reproduce:

1. Enter the demo app
2. Go to Loadable
3. Start "Load all numbers" task
4. Go back

Result: Task is not cancelled
Expected: Task is cancelled

**Comment by SwiftedMind** [comment]
Thanks for reporting!

This is actually expected behavior. Swift Tasks do not cancel automatically when the view disappears. This is something that you have to either do manually in an `.onDisappear` modifier or automatically by using the `.task` modifier. That's just how Concurrency works in Swift (somewhat unintuitively, when working with SwiftUI).

This simple demo does not have long running, never-ending tasks that would cause any leaks, so I omitted the manual cancellation for simplicity.

However, as it happens, I just added a new demo to the example app yesterday that includes automatic cancellation when the view disappears by using the `.task` modifier:

```swift
.task(id: numbersObservationId) {
  await stream()
}
```

If you check out the `main` branch, you can have a look :)
